build(autotools): fixed node test build (#2744)
This fixes this error:
```
test_base.h:64:33: error: ambiguous overload for ‘operator<<’
(operand types are ‘std::basic_ostream<char>’ and ‘std::nullptr_t’)
```

The issue was that in c++17 `std::ostream operator<<(nullptr_t)`
template is already implemented.
Unfortunately, `AX_CXX_COMPILE_STDCXX` does not add the
`-std=c++11` flag, so the compiler can use the newer C++ standard.