fix: missing template argument : compiler in FreeBSD complained
Issued error message:
> error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]

fix #3557