Minor change to stop a doxygen warning.  Doxygen doesn't like the \writeme before a commented prototype.  Complains with these strange warnings:
  .../synfig/src/synfig/canvas.h:383: Error: Unexpected character `4'
  .../synfig/src/synfig/canvas.h:383: Error: Unexpected character `7'

There is no `4' or `7' on line 383, or indeed anywhere in the entire file other than the $Id$ keyword.

git-svn-id: http://svn.voria.com/code@333 1f10aa63-cdf2-0310-b900-c93c546f37ac